### ISSUE TITLE
Entrance placement attempt count exceeded for world 0

### ISSUE THREAD

**Issue by xlogisticsx** [TestRunnerSRL/OoT-Randomizer#1022]
Version 5.2.0 release
String: AJWFG32ESZLAAA6NFTGACEEEGEJELESEYEGKBAE2AGSBJCTEECAJCASED2DJLAA
Seed: 420blazeit

Issue is repeatable for me.

```
Entrance placement attempt count exceeded for world 0
Traceback (most recent call last):
  File "C:\Users\<user>\AppData\Local\Programs\ootr-electron-gui\resources\app\python\OoTRandomizer.py", line 61, in start
    main(settings)
  File "C:\Users\<user>\AppData\Local\Programs\ootr-electron-gui\resources\app\python\Main.py", line 95, in main
    spoiler = generate(settings, window)
  File "C:\Users\<user>\AppData\Local\Programs\ootr-electron-gui\resources\app\python\Main.py", line 148, in generate
    set_entrances(worlds)
  File "C:\Users\<user>\AppData\Local\Programs\ootr-electron-gui\resources\app\python\EntranceShuffle.py", line 305, in set_entrances
    shuffle_random_entrances(worlds)
  File "C:\Users\<user>\AppData\Local\Programs\ootr-electron-gui\resources\app\python\EntranceShuffle.py", line 391, in shuffle_random_entrances
    shuffle_entrance_pool(worlds, entrance_pool, target_entrance_pools[pool_type], locations_to_ensure_reachable)
  File "C:\Users\<user>\AppData\Local\Programs\ootr-electron-gui\resources\app\python\EntranceShuffle.py", line 450, in shuffle_entrance_pool
    raise EntranceShuffleError('Entrance placement attempt count exceeded for world %d' % entrance_pool[0].world.id)
EntranceShuffle.EntranceShuffleError: Entrance placement attempt count exceeded for world 0

```

**Comment by aofengen** [comment]
This error means that the randomizer was never t able to find a valid placement if entrances to gen a seed. Best bet is to keep trying and it will find it eventually. In the future, please come to the discord support channels before creating an issue on the github repository, as this is a well known problem with entrance randomizer seeds. We will be glad to assist you further in the discord

**Comment by BeeLuigi** [comment]
Indeed. Make sure to use a different seed, else it will fail in the same way again.

**Comment by flagrama** [comment]
This is basically linked to #869 as without global retry this is more likely to happen.

I wouldn't say it's a bug with the randomizer itself though. Many seeds, especially with entrance randomizer, will fail several times before it gets one to work, but to keep it from going on forever we limit it to 20 for entrance randomizer attempts I believe. So that seed failed to create a beatable seed 20 times which isn't very surprising.

**Comment by xlogisticsx** [comment]
My apologies for going to the wrong spot to post this. The app said to inform a dev, so I intuitively thought to put it here. Thanks for the info!

**Comment by Nicholas-Steel** [comment]
Could the error message be made clearer for a laymen?
