### ISSUE TITLE
ASM compile-c multiple definitions

### ISSUE THREAD

**Issue by Sirius902** [TestRunnerSRL/OoT-Randomizer#1082]
When attempting to build the C code in `ASM/c` using `python3 ASM/build.py --compile-c` I get this as output.
```
rm -f build/bin/*.o
mkdir -p build/bin
mips64-gcc -o build/bin/agony.o -c c/agony.c -O1 -fno-reorder-blocks -march=vr4300 -mtune=vr4300 -mabi=32 -mno-gpopt -mdivide-breaks -mexplicit-relocs
mips64-gcc -o build/bin/chests.o -c c/chests.c -O1 -fno-reorder-blocks -march=vr4300 -mtune=vr4300 -mabi=32 -mno-gpopt -mdivide-breaks -mexplicit-relocs
mips64-gcc -o build/bin/dpad.o -c c/dpad.c -O1 -fno-reorder-blocks -march=vr4300 -mtune=vr4300 -mabi=32 -mno-gpopt -mdivide-breaks -mexplicit-relocs
mips64-gcc -o build/bin/dungeon_info.o -c c/dungeon_info.c -O1 -fno-reorder-blocks -march=vr4300 -mtune=vr4300 -mabi=32 -mno-gpopt -mdivide-breaks -mexplicit-relocs
mips64-gcc -o build/bin/extern_ctxt.o -c c/extern_ctxt.c -O1 -fno-reorder-blocks -march=vr4300 -mtune=vr4300 -mabi=32 -mno-gpopt -mdivide-breaks -mexplicit-relocs
mips64-gcc -o build/bin/file_select.o -c c/file_select.c -O1 -fno-reorder-blocks -march=vr4300 -mtune=vr4300 -mabi=32 -mno-gpopt -mdivide-breaks -mexplicit-relocs
mips64-gcc -o build/bin/fog.o -c c/fog.c -O1 -fno-reorder-blocks -march=vr4300 -mtune=vr4300 -mabi=32 -mno-gpopt -mdivide-breaks -mexplicit-relocs
mips64-gcc -o build/bin/ganon.o -c c/ganon.c -O1 -fno-reorder-blocks -march=vr4300 -mtune=vr4300 -mabi=32 -mno-gpopt -mdivide-breaks -mexplicit-relocs
mips64-gcc -o build/bin/get_items.o -c c/get_items.c -O1 -fno-reorder-blocks -march=vr4300 -mtune=vr4300 -mabi=32 -mno-gpopt -mdivide-breaks -mexplicit-relocs
mips64-gcc -o build/bin/gfx.o -c c/gfx.c -O1 -fno-reorder-blocks -march=vr4300 -mtune=vr4300 -mabi=32 -mno-gpopt -mdivide-breaks -mexplicit-relocs
mips64-gcc -o build/bin/hud_colors.o -c c/hud_colors.c -O1 -fno-reorder-blocks -march=vr4300 -mtune=vr4300 -mabi=32 -mno-gpopt -mdivide-breaks -mexplicit-relocs
mips64-gcc -o build/bin/icetrap.o -c c/icetrap.c -O1 -fno-reorder-blocks -march=vr4300 -mtune=vr4300 -mabi=32 -mno-gpopt -mdivide-breaks -mexplicit-relocs
mips64-gcc -o build/bin/item_effects.o -c c/item_effects.c -O1 -fno-reorder-blocks -march=vr4300 -mtune=vr4300 -mabi=32 -mno-gpopt -mdivide-breaks -mexplicit-relocs
mips64-gcc -o build/bin/item_table.o -c c/item_table.c -O1 -fno-reorder-blocks -march=vr4300 -mtune=vr4300 -mabi=32 -mno-gpopt -mdivide-breaks -mexplicit-relocs
mips64-gcc -o build/bin/item_upgrades.o -c c/item_upgrades.c -O1 -fno-reorder-blocks -march=vr4300 -mtune=vr4300 -mabi=32 -mno-gpopt -mdivide-breaks -mexplicit-relocs
mips64-gcc -o build/bin/main.o -c c/main.c -O1 -fno-reorder-blocks -march=vr4300 -mtune=vr4300 -mabi=32 -mno-gpopt -mdivide-breaks -mexplicit-relocs
mips64-gcc -o build/bin/menu.o -c c/menu.c -O1 -fno-reorder-blocks -march=vr4300 -mtune=vr4300 -mabi=32 -mno-gpopt -mdivide-breaks -mexplicit-relocs
mips64-gcc -o build/bin/models.o -c c/models.c -O1 -fno-reorder-blocks -march=vr4300 -mtune=vr4300 -mabi=32 -mno-gpopt -mdivide-breaks -mexplicit-relocs
mips64-gcc -o build/bin/rainbow_sword.o -c c/rainbow_sword.c -O1 -fno-reorder-blocks -march=vr4300 -mtune=vr4300 -mabi=32 -mno-gpopt -mdivide-breaks -mexplicit-relocs
mips64-gcc -o build/bin/refill.o -c c/refill.c -O1 -fno-reorder-blocks -march=vr4300 -mtune=vr4300 -mabi=32 -mno-gpopt -mdivide-breaks -mexplicit-relocs
mips64-gcc -o build/bin/scarecrow.o -c c/scarecrow.c -O1 -fno-reorder-blocks -march=vr4300 -mtune=vr4300 -mabi=32 -mno-gpopt -mdivide-breaks -mexplicit-relocs
mips64-gcc -o build/bin/text.o -c c/text.c -O1 -fno-reorder-blocks -march=vr4300 -mtune=vr4300 -mabi=32 -mno-gpopt -mdivide-breaks -mexplicit-relocs
mips64-gcc -o build/bin/triforce.o -c c/triforce.c -O1 -fno-reorder-blocks -march=vr4300 -mtune=vr4300 -mabi=32 -mno-gpopt -mdivide-breaks -mexplicit-relocs
mips64-gcc -o build/bin/util.o -c c/util.c -O1 -fno-reorder-blocks -march=vr4300 -mtune=vr4300 -mabi=32 -mno-gpopt -mdivide-breaks -mexplicit-relocs
mips64-ld -o build/bundle.o -i -L. -l:build/bin/agony.o -l:build/bin/chests.o -l:build/bin/dpad.o -l:build/bin/dungeon_info.o -l:build/bin/extern_ctxt.o -l:build/bin/file_select.o -l:build/bin/fog.o -l:build/bin/ganon.o -l:build/bin/get_items.o -l:build/bin/gfx.o -l:build/bin/hud_colors.o -l:build/bin/icetrap.o -l:build/bin/item_effects.o -l:build/bin/item_table.o -l:build/bin/item_upgrades.o -l:build/bin/main.o -l:build/bin/menu.o -l:build/bin/models.o -l:build/bin/rainbow_sword.o -l:build/bin/refill.o -l:build/bin/scarecrow.o -l:build/bin/text.o -l:build/bin/triforce.o -l:build/bin/util.o
mips64-ld: ./build/bin/dpad.o:(.bss+0x10): multiple definition of `dpad_sprite'; ./build/bin/agony.o:(.bss+0x10): first defined here
mips64-ld: ./build/bin/dpad.o:(.bss+0x40): multiple definition of `items_sprite'; ./build/bin/agony.o:(.bss+0x40): first defined here
mips64-ld: ./build/bin/dpad.o:(.bss+0x0): multiple definition of `triforce_sprite'; ./build/bin/agony.o:(.bss+0x0): first defined here
mips64-ld: ./build/bin/dpad.o:(.bss+0x20): multiple definition of `font_sprite'; ./build/bin/agony.o:(.bss+0x20): first defined here
mips64-ld: ./build/bin/dpad.o:(.bss+0x30): multiple definition of `quest_items_sprite'; ./build/bin/agony.o:(.bss+0x30): first defined here
mips64-ld: ./build/bin/dpad.o:(.bss+0x50): multiple definition of `medals_sprite'; ./build/bin/agony.o:(.bss+0x50): first defined here
mips64-ld: ./build/bin/dpad.o:(.bss+0x60): multiple definition of `stones_sprite'; ./build/bin/agony.o:(.bss+0x60): first defined here
mips64-ld: ./build/bin/dungeon_info.o:(.bss+0x30): multiple definition of `font_sprite'; ./build/bin/agony.o:(.bss+0x20): first defined here
mips64-ld: ./build/bin/dungeon_info.o:(.bss+0x60): multiple definition of `medals_sprite'; ./build/bin/agony.o:(.bss+0x50): first defined here
mips64-ld: ./build/bin/dungeon_info.o:(.bss+0x70): multiple definition of `stones_sprite'; ./build/bin/agony.o:(.bss+0x60): first defined here
mips64-ld: ./build/bin/dungeon_info.o:(.bss+0x40): multiple definition of `quest_items_sprite'; ./build/bin/agony.o:(.bss+0x30): first defined here
mips64-ld: ./build/bin/dungeon_info.o:(.bss+0x10): multiple definition of `triforce_sprite'; ./build/bin/agony.o:(.bss+0x0): first defined here
mips64-ld: ./build/bin/dungeon_info.o:(.bss+0x20): multiple definition of `dpad_sprite'; ./build/bin/agony.o:(.bss+0x10): first defined here
mips64-ld: ./build/bin/dungeon_info.o:(.bss+0x50): multiple definition of `items_sprite'; ./build/bin/agony.o:(.bss+0x40): first defined here
mips64-ld: ./build/bin/file_select.o:(.bss+0x40): multiple definition of `items_sprite'; ./build/bin/agony.o:(.bss+0x40): first defined here
mips64-ld: ./build/bin/file_select.o:(.bss+0x30): multiple definition of `quest_items_sprite'; ./build/bin/agony.o:(.bss+0x30): first defined here
mips64-ld: ./build/bin/file_select.o:(.bss+0x0): multiple definition of `triforce_sprite'; ./build/bin/agony.o:(.bss+0x0): first defined here
mips64-ld: ./build/bin/file_select.o:(.bss+0x10): multiple definition of `dpad_sprite'; ./build/bin/agony.o:(.bss+0x10): first defined here
mips64-ld: ./build/bin/file_select.o:(.bss+0x20): multiple definition of `font_sprite'; ./build/bin/agony.o:(.bss+0x20): first defined here
mips64-ld: ./build/bin/file_select.o:(.bss+0x50): multiple definition of `medals_sprite'; ./build/bin/agony.o:(.bss+0x50): first defined here
mips64-ld: ./build/bin/file_select.o:(.bss+0x60): multiple definition of `stones_sprite'; ./build/bin/agony.o:(.bss+0x60): first defined here
mips64-ld: ./build/bin/gfx.o:(.data+0x90): multiple definition of `stones_sprite'; ./build/bin/agony.o:(.bss+0x60): first defined here
mips64-ld: ./build/bin/gfx.o:(.data+0x80): multiple definition of `medals_sprite'; ./build/bin/agony.o:(.bss+0x50): first defined here
mips64-ld: ./build/bin/gfx.o:(.data+0x70): multiple definition of `items_sprite'; ./build/bin/agony.o:(.bss+0x40): first defined here
mips64-ld: ./build/bin/gfx.o:(.data+0x60): multiple definition of `quest_items_sprite'; ./build/bin/agony.o:(.bss+0x30): first defined here
mips64-ld: ./build/bin/gfx.o:(.data+0x40): multiple definition of `dpad_sprite'; ./build/bin/agony.o:(.bss+0x10): first defined here
mips64-ld: ./build/bin/gfx.o:(.data+0x30): multiple definition of `triforce_sprite'; ./build/bin/agony.o:(.bss+0x0): first defined here
mips64-ld: ./build/bin/gfx.o:(.data+0x50): multiple definition of `font_sprite'; ./build/bin/agony.o:(.bss+0x20): first defined here
mips64-ld: ./build/bin/item_effects.o:(.bss+0x0): multiple definition of `triforce_sprite'; ./build/bin/agony.o:(.bss+0x0): first defined here
mips64-ld: ./build/bin/item_effects.o:(.bss+0x10): multiple definition of `dpad_sprite'; ./build/bin/agony.o:(.bss+0x10): first defined here
mips64-ld: ./build/bin/item_effects.o:(.bss+0x20): multiple definition of `font_sprite'; ./build/bin/agony.o:(.bss+0x20): first defined here
mips64-ld: ./build/bin/item_effects.o:(.bss+0x30): multiple definition of `quest_items_sprite'; ./build/bin/agony.o:(.bss+0x30): first defined here
mips64-ld: ./build/bin/item_effects.o:(.bss+0x40): multiple definition of `items_sprite'; ./build/bin/agony.o:(.bss+0x40): first defined here
mips64-ld: ./build/bin/item_effects.o:(.bss+0x50): multiple definition of `medals_sprite'; ./build/bin/agony.o:(.bss+0x50): first defined here
mips64-ld: ./build/bin/item_effects.o:(.bss+0x60): multiple definition of `stones_sprite'; ./build/bin/agony.o:(.bss+0x60): first defined here
mips64-ld: ./build/bin/item_table.o:(.bss+0x0): multiple definition of `triforce_sprite'; ./build/bin/agony.o:(.bss+0x0): first defined here
mips64-ld: ./build/bin/item_table.o:(.bss+0x10): multiple definition of `dpad_sprite'; ./build/bin/agony.o:(.bss+0x10): first defined here
mips64-ld: ./build/bin/item_table.o:(.bss+0x20): multiple definition of `font_sprite'; ./build/bin/agony.o:(.bss+0x20): first defined here
mips64-ld: ./build/bin/item_table.o:(.bss+0x30): multiple definition of `quest_items_sprite'; ./build/bin/agony.o:(.bss+0x30): first defined here
mips64-ld: ./build/bin/item_table.o:(.bss+0x40): multiple definition of `items_sprite'; ./build/bin/agony.o:(.bss+0x40): first defined here
mips64-ld: ./build/bin/item_table.o:(.bss+0x50): multiple definition of `medals_sprite'; ./build/bin/agony.o:(.bss+0x50): first defined here
mips64-ld: ./build/bin/item_table.o:(.bss+0x60): multiple definition of `stones_sprite'; ./build/bin/agony.o:(.bss+0x60): first defined here
mips64-ld: ./build/bin/main.o:(.bss+0x0): multiple definition of `triforce_sprite'; ./build/bin/agony.o:(.bss+0x0): first defined here
mips64-ld: ./build/bin/main.o:(.bss+0x10): multiple definition of `dpad_sprite'; ./build/bin/agony.o:(.bss+0x10): first defined here
mips64-ld: ./build/bin/main.o:(.bss+0x20): multiple definition of `font_sprite'; ./build/bin/agony.o:(.bss+0x20): first defined here
mips64-ld: ./build/bin/main.o:(.bss+0x30): multiple definition of `quest_items_sprite'; ./build/bin/agony.o:(.bss+0x30): first defined here
mips64-ld: ./build/bin/main.o:(.bss+0x40): multiple definition of `items_sprite'; ./build/bin/agony.o:(.bss+0x40): first defined here
mips64-ld: ./build/bin/main.o:(.bss+0x50): multiple definition of `medals_sprite'; ./build/bin/agony.o:(.bss+0x50): first defined here
mips64-ld: ./build/bin/main.o:(.bss+0x60): multiple definition of `stones_sprite'; ./build/bin/agony.o:(.bss+0x60): first defined here
mips64-ld: ./build/bin/text.o:(.bss+0x20): multiple definition of `font_sprite'; ./build/bin/agony.o:(.bss+0x20): first defined here
mips64-ld: ./build/bin/text.o:(.bss+0x0): multiple definition of `triforce_sprite'; ./build/bin/agony.o:(.bss+0x0): first defined here
mips64-ld: ./build/bin/text.o:(.bss+0x10): multiple definition of `dpad_sprite'; ./build/bin/agony.o:(.bss+0x10): first defined here
mips64-ld: ./build/bin/text.o:(.bss+0x30): multiple definition of `quest_items_sprite'; ./build/bin/agony.o:(.bss+0x30): first defined here
mips64-ld: ./build/bin/text.o:(.bss+0x40): multiple definition of `items_sprite'; ./build/bin/agony.o:(.bss+0x40): first defined here
mips64-ld: ./build/bin/text.o:(.bss+0x50): multiple definition of `medals_sprite'; ./build/bin/agony.o:(.bss+0x50): first defined here
mips64-ld: ./build/bin/text.o:(.bss+0x60): multiple definition of `stones_sprite'; ./build/bin/agony.o:(.bss+0x60): first defined here
mips64-ld: ./build/bin/triforce.o:(.bss+0x20): multiple definition of `font_sprite'; ./build/bin/agony.o:(.bss+0x20): first defined here
mips64-ld: ./build/bin/triforce.o:(.bss+0x0): multiple definition of `triforce_sprite'; ./build/bin/agony.o:(.bss+0x0): first defined here
mips64-ld: ./build/bin/triforce.o:(.bss+0x10): multiple definition of `dpad_sprite'; ./build/bin/agony.o:(.bss+0x10): first defined here
mips64-ld: ./build/bin/triforce.o:(.bss+0x30): multiple definition of `quest_items_sprite'; ./build/bin/agony.o:(.bss+0x30): first defined here
mips64-ld: ./build/bin/triforce.o:(.bss+0x40): multiple definition of `items_sprite'; ./build/bin/agony.o:(.bss+0x40): first defined here
mips64-ld: ./build/bin/triforce.o:(.bss+0x50): multiple definition of `medals_sprite'; ./build/bin/agony.o:(.bss+0x50): first defined here
mips64-ld: ./build/bin/triforce.o:(.bss+0x60): multiple definition of `stones_sprite'; ./build/bin/agony.o:(.bss+0x60): first defined here
make: *** [Makefile:33: bundle] Error 1
Traceback (most recent call last):
  File "ASM/build.py", line 39, in <module>
    call(clist)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2.
```

**Comment by Cuphat** [comment]
Yeah, I think this needs to be looked at. It's an issue with the latest toolchain. I was able to get around it a while back by using a slightly older toolchain. For your specific case, the following version works for me:

Commit `2ec4d98dc46e6623b4cd29f2fccfca5496bac0a4`
Edit the makefile to set the following versions after ./configure:
> BINUTILS_VERSION              = binutils-2.34
GCC_VERSION                   = gcc-9.3.0
NEWLIB_VERSION                = newlib-3.3.0
GDB_VERSION                   = gdb-9.1

**Comment by Sirius902** [comment]
@Cuphat Thanks for the workaround, I managed to get the build script to work using glankk/n64 master by changing the versions in the makefile as you suggested.

**Comment by Cuphat** [comment]
Ah, current commit, then? I'm assuming it's an incompatibility with GCC 10.x.

**Comment by Sirius902** [comment]
@Cuphat I think that's correct, I tried re-making and installing master but this time only changing gcc to `gcc-9.3.0` and it works.
