### ISSUE TITLE
Error on ROM generation

### ISSUE THREAD

**Issue by ThomasCapella** [TestRunnerSRL/OoT-Randomizer#1103]
When I try to generate a rom it gives me AttributeError: 'Name' object has no attribute 'value'

'Name' object has no attribute 'value'
Traceback (most recent call last):
  File "D:\Tom\Programs\StandAlone\Ocarina of Time Randomizer\OoT-Randomizer-5.2.53\OoT-Randomizer-5.2.53\OoTRandomizer.py", line 62, in start
    main(settings)
  File "D:\Tom\Programs\StandAlone\Ocarina of Time Randomizer\OoT-Randomizer-5.2.53\OoT-Randomizer-5.2.53\Main.py", line 96, in main
    spoiler = generate(settings, window)
  File "D:\Tom\Programs\StandAlone\Ocarina of Time Randomizer\OoT-Randomizer-5.2.53\OoT-Randomizer-5.2.53\Main.py", line 128, in generate
    create_dungeons(world)
  File "D:\Tom\Programs\StandAlone\Ocarina of Time Randomizer\OoT-Randomizer-5.2.53\OoT-Randomizer-5.2.53\DungeonList.py", line 117, in create_dungeons
    world.load_regions_from_json(dungeon_json)
  File "D:\Tom\Programs\StandAlone\Ocarina of Time Randomizer\OoT-Randomizer-5.2.53\OoT-Randomizer-5.2.53\World.py", line 332, in load_regions_from_json
    self.parser.parse_spot_rule(new_exit)
  File "D:\Tom\Programs\StandAlone\Ocarina of Time Randomizer\OoT-Randomizer-5.2.53\OoT-Randomizer-5.2.53\RuleParser.py", line 465, in parse_spot_rule
    access_rule = self.parse_rule(rule, spot)
  File "D:\Tom\Programs\StandAlone\Ocarina of Time Randomizer\OoT-Randomizer-5.2.53\OoT-Randomizer-5.2.53\RuleParser.py", line 460, in parse_rule
    return self.make_access_rule(self.visit(ast.parse(rule_string, mode='eval').body))
  File "C:\Program Files\Python39\lib\ast.py", line 407, in visit
    return visitor(node)
  File "D:\Tom\Programs\StandAlone\Ocarina of Time Randomizer\OoT-Randomizer-5.2.53\OoT-Randomizer-5.2.53\RuleParser.py", line 284, in visit_BoolOp
    elt = self.visit(elt)
  File "C:\Program Files\Python39\lib\ast.py", line 407, in visit
    return visitor(node)
  File "D:\Tom\Programs\StandAlone\Ocarina of Time Randomizer\OoT-Randomizer-5.2.53\OoT-Randomizer-5.2.53\RuleParser.py", line 284, in visit_BoolOp
    elt = self.visit(elt)
  File "C:\Program Files\Python39\lib\ast.py", line 407, in visit
    return visitor(node)
  File "D:\Tom\Programs\StandAlone\Ocarina of Time Randomizer\OoT-Randomizer-5.2.53\OoT-Randomizer-5.2.53\RuleParser.py", line 212, in visit_Subscript
    slice=ast.Index(value=ast.Str(node.slice.value.id.replace('_', ' '))),
AttributeError: 'Name' object has no attribute 'value'

**Comment by Zannick** [comment]
This looks like a python 3.9 change in AST makeup, and 3.9 [isn't released yet](https://www.python.org/dev/peps/pep-0596/), so a fix for this won't be coming very soon. We currently only support python 3.6-3.8.

**Comment by LostThePirate** [comment]
In the future, this sort of concern is generally better handled in our community Discord server ( discord.gg/ootrandomizer ); they can identify known issues and help you troubleshoot things much more quickly than here on GitHub.

**Comment by ThomasCapella** [comment]
Thank you.
