### ISSUE TITLE
'Name' object has no attribute 'value'

### ISSUE THREAD

**Issue by Cutse** [TestRunnerSRL/OoT-Randomizer#1160]
Released version of the OoT Randomizer found here: https://ootrandomizer.com/downloads for windows encounters errors during seed generation:

`'Name' object has no attribute 'value'

Traceback (most recent call last):

  File "C:\Users\[hidden]\AppData\Local\Programs\ootr-electron-gui\resources\app\python\OoTRandomizer.py", line 61, in start
    main(settings)

  File "C:\Users\[hidden]\AppData\Local\Programs\ootr-electron-gui\resources\app\python\Main.py", line 95, in main
    spoiler = generate(settings, window)

  File "C:\Users\[hidden]\AppData\Local\Programs\ootr-electron-gui\resources\app\python\Main.py", line 126, in generate
    create_dungeons(world)

  File "C:\Users\[hidden]\AppData\Local\Programs\ootr-electron-gui\resources\app\python\DungeonList.py", line 117, in create_dungeons
    world.load_regions_from_json(dungeon_json)

  File "C:\Users\[hidden]\AppData\Local\Programs\ootr-electron-gui\resources\app\python\World.py", line 239, in load_regions_from_json
    self.parser.parse_spot_rule(new_exit)

  File "C:\Users\[hidden]\AppData\Local\Programs\ootr-electron-gui\resources\app\python\RuleParser.py", line 458, in parse_spot_rule
    spot.access_rule = self.parse_rule(rule, spot)

  File "C:\Users\[hidden]\AppData\Local\Programs\ootr-electron-gui\resources\app\python\RuleParser.py", line 453, in parse_rule
    return self.make_access_rule(self.visit(ast.parse(rule_string, mode='eval').body))

  File "E:\[hidden]\Game Creation Software\Python\lib\ast.py", line 407, in visit
    return visitor(node)

  File "C:\Users\[hidden]\AppData\Local\Programs\ootr-electron-gui\resources\app\python\RuleParser.py", line 284, in visit_BoolOp
    elt = self.visit(elt)

  File "E:\[hidden]\Game Creation Software\Python\lib\ast.py", line 407, in visit
    return visitor(node)

  File "C:\Users\[hidden]\AppData\Local\Programs\ootr-electron-gui\resources\app\python\RuleParser.py", line 284, in visit_BoolOp
    elt = self.visit(elt)

  File "E:\[hidden]\Game Creation Software\Python\lib\ast.py", line 407, in visit
    return visitor(node)

  File "C:\Users\[hidden]\AppData\Local\Programs\ootr-electron-gui\resources\app\python\RuleParser.py", line 212, in visit_Subscript
    slice=ast.Index(value=ast.Str(node.slice.value.id.replace('_', ' '))),

AttributeError: 'Name' object has no attribute 'value'`

**Comment by ETR-BTF** [comment]
Uninstall python 3.9 and install python 3.8.
https://www.python.org/downloads/release/python-386/?hn

In the future please visit our discord's support channel first. ;)
https://discord.gg/q6m6kzK

**Comment by Zannick** [comment]
The current release is not compatible with Python 3.9. This is already fixed in Dev.
