### ISSUE TITLE
Spoiler Key barren_regions Not Handled Properly By Plando

### ISSUE THREAD

**Issue by flagrama** [TestRunnerSRL/OoT-Randomizer#1185]
https://github.com/TestRunnerSRL/OoT-Randomizer/blob/53aff3b99b83e63bdfe9c3695487a4ed4e499aa2/Plandomizer.py#L875

This fragment of code assumes all keys in the source dictionary provide dictionaries themselves. However, `barren_regions` is a list so if it is included in a plando file, including generated spoiler logs, it will throw an exception when trying to get `barren_regions` "items" for the new source dictionary.

```python
'list' object has no attribute 'items'
Traceback (most recent call last):
  File "/home/vcunningham/Development/OoT-Randomizer/OoTRandomizer.py", line 62, in start
    main(settings)
  File "/home/vcunningham/Development/OoT-Randomizer/Main.py", line 51, in main
    rom = resolve_settings(settings, window=window)
  File "/home/vcunningham/Development/OoT-Randomizer/Main.py", line 74, in resolve_settings
    settings.load_distribution()
  File "/home/vcunningham/Development/OoT-Randomizer/Settings.py", line 195, in load_distribution
    self.distribution = Distribution.from_file(self, self.distribution_file)
  File "/home/vcunningham/Development/OoT-Randomizer/Plandomizer.py", line 1028, in from_file
    return Distribution(settings, src_dict)
  File "/home/vcunningham/Development/OoT-Randomizer/Plandomizer.py", line 816, in __init__
    self.reset()
  File "/home/vcunningham/Development/OoT-Randomizer/Plandomizer.py", line 876, in reset
    src_all = {key: val for key, val in self.src_dict[k].items() if key not in world_names}
AttributeError: 'list' object has no attribute 'items'
```

**Comment by Zannick** [comment]
One easy fix is to check that whether `self.src_dict[k]` is a dict beforehand and pass it to `update` in its entirety if it's not, but we're not actually using the values of `':woth_locations` or `:barren_regions` at all because they're output-only. So maybe we'll just skip them in `reset`.

https://github.com/TestRunnerSRL/OoT-Randomizer/blob/53aff3b99b83e63bdfe9c3695487a4ed4e499aa2/Plandomizer.py#L221-L247

Note how the `update_dict` has the keys without the `:` too, so we just discard them all via the `if k in update_dict` check. The keys exist in `update_dict` like that to clear them on reset.

**Comment by Zannick** [comment]
I guess we can do both, though the `else` case would be inactive.
