### ISSUE TITLE
Error plandoing Broken Sword onto free Song from Impa

### ISSUE THREAD

**Issue by fenhl** [TestRunnerSRL/OoT-Randomizer#1341]
Running the randomizer with the following plando file:

```json
{
    "settings": {
        "skip_child_zelda": true,
        "shuffle_song_items": "any"
    },
    "locations": {
        "Song from Impa": "Broken Sword"
    }
}
```

results in this error:

```
OoT Randomizer Version 6.0.57 f.LUM  -  Seed: Q40OD6W79D
(Original) Settings string: AJLSXFCSKASDJAAZNJAAANCUSWJAAAAAAJCAASGSEFAA

Generating World 1.
Creating Overworld
Calculating Access Rules.
Generating Item Pool.
Setting Entrances.
Fill the world.
Placing dungeon items.
Placing progression items.
Placing priority items.
Placing the rest of the items.
Calculating playthrough.
Collected 25 spheres
Collected 21 final spheres
Calculating hint data.
Patching ROM.
'broken_knife'
Traceback (most recent call last):
  File "C:\Users\fenhl\git\github.com\fenhl\OoT-Randomizer\stage\OoTRandomizer.py", line 62, in start
    main(settings)
  File "C:\Users\fenhl\git\github.com\fenhl\OoT-Randomizer\stage\Main.py", line 65, in main
    patch_and_output(settings, window, spoiler, rom)
  File "C:\Users\fenhl\git\github.com\fenhl\OoT-Randomizer\stage\Main.py", line 267, in patch_and_output
    patch_rom(spoiler, worlds[settings.player_num - 1], rom)
  File "C:\Users\fenhl\git\github.com\fenhl\OoT-Randomizer\stage\Patches.py", line 1761, in patch_rom
    save_context.write_save_table(rom)
  File "C:\Users\fenhl\git\github.com\fenhl\OoT-Randomizer\stage\SaveContext.py", line 186, in write_save_table
    self.write_save_entry(address)
  File "C:\Users\fenhl\git\github.com\fenhl\OoT-Randomizer\stage\SaveContext.py", line 152, in write_save_entry
    self.write_save_entry(sub_address)
  File "C:\Users\fenhl\git\github.com\fenhl\OoT-Randomizer\stage\SaveContext.py", line 157, in write_save_entry
    address.get_writes(self)
  File "C:\Users\fenhl\git\github.com\fenhl\OoT-Randomizer\stage\SaveContext.py", line 79, in get_writes
    value = self.get_value_raw()
  File "C:\Users\fenhl\git\github.com\fenhl\OoT-Randomizer\stage\SaveContext.py", line 41, in get_value_raw
    value = self.choices[value]
KeyError: 'broken_knife'
```

**Comment by fenhl** [comment]
There are other items that don't work on free Song from Impa, like Deku Nuts (5), but those give a better error message:

> RuntimeError: Cannot assign item Deku Nuts (5) to location Song from Impa.
