### ISSUE TITLE
Module 'random' has no attribute 'choices'

### ISSUE THREAD

**Issue by aplumafreak500** [TestRunnerSRL/OoT-Randomizer#188]
```
Traceback (most recent call last):
  File "OoTRandomizer.py", line 65, in <module>
    start()
  File "OoTRandomizer.py", line 25, in start
    settings, gui, args_loglevel = get_settings_from_command_line_args()
  File "/home/overflow/git/OoT-Randomizer-Dev/Settings.py", line 2113, in get_settings_from_command_line_args
    settings = Settings(result)
  File "/home/overflow/git/OoT-Randomizer-Dev/Settings.py", line 154, in __init__
    self.seed = ''.join(random.choices(string.ascii_uppercase + string.digits, k=10))
AttributeError: module 'random' has no attribute 'choices'
```

Python 3.5.2, Ubuntu 16.04.

Edit: Manually supplying a seed works fine.

**Comment by r0bd0g** [comment]
This build requires python 3.6

**Comment by TestRunnerSRL** [comment]
I wasn't aware I was supposed to support 3.5... Not sure if this is something I want to fix lol

**Comment by TestRunnerSRL** [comment]
Well there was a PR to fix this, so now it should be fixed.
