### ISSUE TITLE
Shop Data Gets Corrupted With Some Item Combinations

### ISSUE THREAD

**Issue by flagrama** [TestRunnerSRL/OoT-Randomizer#2122]
On 7.1.198 f.LUM the following settings string (with modifications to allow a string longer than 1024 bytes)
```
BSA4BGBSL62ANMTDDSNQFQNA4QMANCEGJLAQKAAAAASJVSJC68M79XAACAGASAJBADAHASAJB2CAGAPA6A6BAESJAUAGBSCJFAMAZASBEDSGSPA6A4B2D2HASABBECNEAKSUAGBQCAFJLAXAMB2CWFSMSZASBCDJG2NA4AYBQDAHJQA7A5B2DWHSRS9AACCEJJ2SACBFCNE6JAUSEBLCYESKJVAHBRCAFELSWSKBWCLF2L2XANB3CWFNMAZSQB8C8FANJ2ATBDDJGWNS3SVBJDUGJP24AYBPD6G6PA6S2BUDGHSQJ7A5BZDSHERS8S7B6D4H2R29AACBEEJNSABTCCGEQJATJCBFCME2JWTSDTHCSECKJU2EBLCXENK6UAGTNC4EYKSVJHBRC9EALEWSJTTCEFLL2W2KBWC7G6P65A2TSDCHGQS6J3BVDHHSQE7S4TXDNH4Q2725B2DTHERN8A7T4DYHQRA9J8B7D5H2RW9S9T9DAJCSJA3ACCEFJNS6ABCUEELJYSSBKDCHERJATECTEUKEWJLT2C3FCNE3JWTNDBHUQE8J8TAEKJCTEDKJUWETKUVEJKUUJF3LCYEPK6U6FBNU2EUKGVSGKPC5EZKSVEHTQU7E6K4V2H3RCAFBLEWNJBTUCFGLQWAKKUCFFML2WWKTVUHFSLCXJL3WCLFXLNX6LBYUNF4LYXSMKZCRF9LAYENT2UTFEMLY2N33CWFKMWYNPB5UYFQM8YAQK6C3FVMJZWQT7U5F2MUZJR38C8F7M6Z6RBAVAGCNG2SSKBDDGHNS2ETTCVFGNN422T3DDJGTNE3NUBFVLGYNQ3AVKGDPG5N23WVTHVRGAPC4JW3JDUGFPN46WBLVWGLPY4SXKMDZGRPA5EYTNV3GWPL52Y3PD6G3PW5NZBRV8G8P85A2KSDBHDQJ6W2TTVDHJQU6J33UDGHPQ6663BWVJHUQG7S4KXDMHZQS7E5TYVPH6Q47253ZDSHBRE8N6B3VUHGRQ8A7K4DXHMR28W7T5VZHSRC9J836D4HXRN968B8V6H4RY9S9K9D9H9RAAFAUAWBJESLA3A4BEEJKSWAPBCDWGJQS8ABCLEEKJVSJBXCUFWMJ2SUBKD4GEQJ7S6B7DCJWSJCTGCTELKEVJHTSCFFULWXJWULF3L4XENK3UWFPMCZWQK8U8FBNL2ETKDVJGXNU3WVKJVJ44YFAAAAAAAAAFQACAJHAATBBSSSFUR
```
is a combination that pretty consistently produces the error
```
can't convert negative int to unsigned
Traceback (most recent call last):
  File "/home/vcunningham/Development/OoT-Randomizer/OoTRandomizer.py", line 58, in start
    main(settings)
  File "/home/vcunningham/Development/OoT-Randomizer/Main.py", line 57, in main
    patch_and_output(settings, spoiler, rom)
  File "/home/vcunningham/Development/OoT-Randomizer/Main.py", line 322, in patch_and_output
    patch_cosmetics_log = prepare_rom(spoiler, world, rom, settings, rng_state, restore_rom)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vcunningham/Development/OoT-Randomizer/Main.py", line 202, in prepare_rom
    patch_rom(spoiler, world, rom)
  File "/home/vcunningham/Development/OoT-Randomizer/Patches.py", line 2462, in patch_rom
    write_shop_items(rom, shop_item_file.start + 0x1DEC, shop_items)
  File "/home/vcunningham/Development/OoT-Randomizer/Messages.py", line 1078, in write_shop_items
    s.write(rom, shop_table_address, s.index)
  File "/home/vcunningham/Development/OoT-Randomizer/Messages.py", line 1048, in write
    data += int_to_bytes(self.model, 2)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vcunningham/Development/OoT-Randomizer/Messages.py", line 616, in int_to_bytes
    return int.to_bytes(num, width, byteorder='big', signed=signed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: can't convert negative int to unsigned
```
RealRob believes this is related to the child trade shuffle.

**Comment by cjohnson57** [comment]
Fixed with merging #2123
