### ISSUE TITLE
Can't patch roms with shopsanity

### ISSUE THREAD

**Issue by Hamsda** [TestRunnerSRL/OoT-Randomizer#315]
We tried creating a shopsanity multi world earlier and it hit us with the following error
```
Traceback (most recent call last):
  File "D:\OoT Randomizer TR\GuiUtils.py", line 30, in try_run
    code_to_run(*code_arg)
  File "D:\OoT Randomizer TR\Main.py", line 151, in main
    patch_rom(spoiler, world, rom)
  File "D:\OoT Randomizer TR\Patches.py", line 1268, in patch_rom
    world.get_region('Kakariko Potion Shop Front').locations)
  File "D:\OoT Randomizer TR\Patches.py", line 1766, in place_shop_items
    shop_item.model = location.item.model - 1
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int' 
```
Not sure why an items model would suddenly be none, considering the blame said the file wasn't modified in the last 20 odd days.

**Comment by TestRunnerSRL** [comment]
this is fixed
