### ISSUE TITLE
Base ROM is uncompressed

### ISSUE THREAD

**Issue by joeauty** [TestRunnerSRL/OoT-Randomizer#325]
Running on OS X I'm now getting this error. This was not happening before with this fork, nor is it happening with the master branch parent project (https://github.com/AmazingAmpharos/OoT-Randomizer)

```
Traceback (most recent call last):
  File "/Users/joe/OoT-Randomizer-fork/GuiUtils.py", line 30, in try_run
    code_to_run(*code_arg)
  File "/Users/joe/OoT-Randomizer-fork/Main.py", line 55, in main
    rom = LocalRom(settings)
  File "/Users/joe/OoT-Randomizer-fork/Rom.py", line 30, in __init__
    self.decompress_rom_file(file, decomp_file)
  File "/Users/joe/OoT-Randomizer-fork/Rom.py", line 82, in decompress_rom_file
    raise RuntimeError('Base ROM is uncompressed. Please provide an original ROM.')
RuntimeError: Base ROM is uncompressed. Please provide an original ROM.
```

**Comment by TestRunnerSRL** [comment]
You must provide the original ROM as your base rom, not an unpressed rom produced from the rando. So `ZOOTDEC.z64` is not acceptable.
