### ISSUE TITLE
Master Quest Roms not generating

### ISSUE THREAD

**Issue by rilllan** [TestRunnerSRL/OoT-Randomizer#73]
Currently if you select either mixed or master quest, the rom will not generate giving this error.
RuntimeError: No such location GS Deku Tree Basement Back Room

And here is the Traceback:
Traceback (most recent call last):
  File "C:\Users\Rillan\Documents\Game Randomizers\OoT-Randomizer-Dev2-15-46f\GuiUtils.py", line 30, in try_run
    code_to_run(*code_arg)
  File "C:\Users\Rillan\Documents\Game Randomizers\OoT-Randomizer-Dev2-15-46f\Main.py", line 87, in main
    set_rules(world)
  File "C:\Users\Rillan\Documents\Game Randomizers\OoT-Randomizer-Dev2-15-46f\Rules.py", line 6, in set_rules
    global_rules(world)
  File "C:\Users\Rillan\Documents\Game Randomizers\OoT-Randomizer-Dev2-15-46f\Rules.py", line 69, in global_rules
    dung_rules_dt0(world)
  File "C:\Users\Rillan\Documents\Game Randomizers\OoT-Randomizer-Dev2-15-46f\Rules.py", line 294, in dung_rules_dt0
    set_rule(world.get_location('GS Deku Tree Basement Back Room'), lambda state: state.has('Boomerang') and (state.has('Bomb Bag') or (state.has_bombchus() and state.can_leave_forest())))
  File "C:\Users\Rillan\Documents\Game Randomizers\OoT-Randomizer-Dev2-15-46f\BaseClasses.py", line 156, in get_location
    raise RuntimeError('No such location %s' % location)
RuntimeError: No such location GS Deku Tree Basement Back Room

Just looking at the code it seems that none of the masterquest dungeon rules are currently entered in the Rules.py 

Also here is the setting string: DJDX6MWCAAAUB

**Comment by TestRunnerSRL** [comment]
Master Quest is not implemented yet
