### ISSUE TITLE
Node JS GUI boot freezing

### ISSUE THREAD

**Issue by IntrinsicNerd** [TestRunnerSRL/OoT-Randomizer#826]
Every time I've tried to run the newest version of the randomizer, I get stuck on creating environment, with the error " ERR! Error: EPERM: operation not permitted, unlink" and then it gives me a different file path every time. 

For example: "npm ERR! Error: EPERM: operation not permitted, unlink 'OoT-Randomizer-4.15.22\GUI\node_modules\.staging\less-b550e71a\package.json'"

**Comment by KevinPal** [comment]
Sounds like a file permission error. Where have you downloaded this?

**Comment by IntrinsicNerd** [comment]
I've tried it both inside of a folder where I keep all of my game related stuff, and also my desktop, which gives me a different error that still freezes progress.

WARN tar ENOENT: no such file or directory, open 'C:\Users\Nick\Desktop\OoT-Randomizer-4.15.22\GUI\node_modules\.staging\@angular\material-40d32d56\input\typings\input-errors.d.ts'

**Comment by IntrinsicNerd** [comment]
I now have the most recent version of Python, Node.js, and npm, and when I run it from my desktop I got it to complete set up one time (out of who knows how many) and instead of continuing, I get this error

Environment setup completed
Error: GUI/node_modules/.bin folder is missing. Please delete the entire GUI/node_modules folder and try again!
    at main (C:\Users\Nick\Desktop\OoT-Randomizer-4.15.22\GUI\run.js:312:15)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)

**Comment by flagrama** [comment]
Try updating to the newest version of the rando and see what errors you get. It should now have a more verbose output when npm is installing things.

**Comment by IntrinsicNerd** [comment]
[892019 513 error.txt](https://github.com/TestRunnerSRL/OoT-Randomizer/files/3488168/892019.513.error.txt) here is my most recent error log

**Comment by Skolvek** [comment]
Late to the party, but I have dealt with something similar... 

based on this message from the error log:
`npm ERR! network request to https://registry.npmjs.org/electron-to-chromium/-/electron-to-chromium-1.3.221.tgz failed, reason: getaddrinfo ENOTFOUND registry.npmjs.org`

what is happening here (I think) is npm is trying to fetch a package from the web (the .tar.gz) file but it is not configured to do so. 

try running the following command to fix this:
`npm config set registry https://registry.npmjs.org/` 

npm pulls a whole bunch of stuff from the web (as you can see in the hundreds of lines before this), some packages will require you to configure the npm installer to point to where you want to download modules from. 

the rest of this error message is your friend as well if that doesn't solve it
`npm
ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'` (this line in particular)

**Comment by BenjaminBrandmeier** [comment]
I was looking for open GUI issues to be fixed, but this issue is very outdated, especially with the latest GUI-Upgrades.

@Cuphat can you close this?
